### ISSUE TITLE
MIKP issues

### ISSUE THREAD

**Issue by umurr** [gokhanceyhan/MOIP_Solvers#10]
We have tried to use solver with 10 instances and there are some problems. The instances are knapsack problems with 5 objectives with half of the variables are continuous and the other half is integer. Each instance has 1 constraint.

Problems:
1. Instance 6 is given as an input to TDA solver with 600 seconds time limit. For the coverage gap 0.05, it worked and gave a reasonable result (JOB ID: 866). However, for the coverage gaps 0.1, 0.15 and 0.2 (JOB IDs: 739, 867, 868), we got error saying "FailedToSolveSingleObjProblem".
2. For each TDA solution, first NDP of the output was seen as a negative point even though the decision variables and parameters are all nonnegative (JOB IDs: 734-743). Another problem is that for each TDA, nadir point is estimated as (0,0,0,0,0) by the solver. We believe these two issues might be related.
3. Instance 2 is given as an input to TDA solver, 600 seconds time limit, 0.1 coverage gap three times (JOB ID: 735, 744 and 758). However it is solved in 3368.57 seconds (in 735) and the other two had similar exceeding solver times. A similar case is for Instance 1, 600 seconds and 0.2 coverage gap limit, it is solved in 4421.30 seconds.
4. We don't exactly know how estimation of ideal points is made but maximum of single objectives of the nondominated points of the output was more than the estimated ideal point. For example, in the NDP points found for instance 1, maximum of the third objectives are 1838.2 and 1854.41 for TDA and SBA solutions (JOB ID: 734 and 746). But both of their ideal point estimation on objective 3 is 1773, lower than the objective 3 of NDP's.

[instances.zip](https://github.com/gokhanceyhan/MOIP_Solvers/files/2035983/instances.zip)

**Comment by umurr** [comment]
Addition:

5- For all TDA solutions (JOB ID: 734 and 746), nadir point is estimated as (0,0,0,0,0) by the solver. This might be related with issue 4 above.

**Comment by gokhanceyhan** [comment]
Addition:

5- For all TDA solutions (JOB ID: 734 and 746), nadir point is estimated as (0,0,0,0,0) by the solver. This might be related with issue 4 above.

**Comment by gokhanceyhan** [comment]
I could not replicate the problem with instances 2 and 6 under the specified parameters on my macbook. I am going to check out the jobs in the server. By the way, the user specifies the objective function in the model file wrong. For a 5-objective problem, it must be specified as ... + 0.0001z5 + z6

**Comment by gokhanceyhan** [comment]
The problem seems to be due to wrong specification of objective functions. With the last update on the objective handling part, the problems are resolved. Solution time can exceed 600 because it is a time limit on a single model to be solved, not on the whole algorithm.
